// Optional secrets (wrangler secret put / local .env). Not generated by `wrangler types`.
interface Env {
  TAVILY_API_KEY?: string;
  BRAVE_SEARCH_API_KEY?: string;
}
declare namespace Cloudflare {
  interface Env {
    TAVILY_API_KEY?: string;
    BRAVE_SEARCH_API_KEY?: string;
  }
}
